version: "3"
services:
  chromadb:
    image: chromadb/chroma:0.6.4.dev119
    environment:
      - ANONYMIZED_TELEMETRY=False
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
    volumes:
      - chroma-data:/chroma/chroma
# Uncomment this if the port does not work
#    ports:
#      - "8000"
    networks:
      - rag-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 10s
      retries: 3

  etl:
    build: ./etl
    env_file: .env
    environment:
      CHROMADB_HOST: chromadb
      CHROMADB_PORT: 8000
      SCRAPING_OUTPUT_DIR: ./data
      SCRAPING_URLS: "https://www.eventbrite.com/d/poland/other--events/?page=1, https://www.eventbrite.com/d/poland/all-events/?subcategories=4004&page=1, https://www.eventbrite.com/d/poland/science-and-tech--events/?page=1, https://crossweb.pl/wydarzenia/, https://unikonferencje.pl/konferencje/technologie_informacyjne, https://unikonferencje.pl/konferencje/elektrotechnika, https://unikonferencje.pl/konferencje/automatyka_robotyka, https://unikonferencje.pl/konferencje/informatyka_teoretyczna"
    networks:
      - rag-net
    volumes:
      - etl-data:/app/data
      - chroma-data:/chroma
    depends_on:
      chromadb:
        condition: service_healthy

  frontend:
    build: ./frontend
    env_file: .env
    environment:
      CHROMADB_HOST: chromadb
      CHROMADB_PORT: 8000
      SCRAPING_OUTPUT_DIR: ./data
    ports:
      - "127.0.0.1:8501:8501"
    networks:
      - rag-net
    volumes:
      - etl-data:/app/data
      - chroma-data:/chroma
    depends_on:
      etl:
        condition: service_completed_successfully

volumes:
  chroma-data:
    driver: local
  etl-data:

networks:
  rag-net: