services:
  chromadb:
    image: chromadb/chroma:0.6.4.dev119
    environment:
      - ANONYMIZED_TELEMETRY=False
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
    volumes:
      - chroma-data:/chroma/chroma
    networks:
      - rag-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 10s
      retries: 3

  etl:
    build: ./etl
    env_file: .env
    networks:
      - rag-net
    volumes:
      - etl-data:/app/data
      - chroma-data:/app/chroma
      - timestamp:/app/timestamp
    depends_on:
      chromadb:
        condition: service_healthy

  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "127.0.0.1:8501:8501"
    networks:
      - rag-net
    volumes:
      - etl-data:/app/data
    depends_on:
      etl:
        condition: service_completed_successfully

volumes:
  chroma-data:
  etl-data:
  timestamp:

networks:
  rag-net: